### ISSUE TITLE
loading model incorrectly

### ISSUE THREAD

**Issue by baolonghnu** [arcchang1236/CA-NoiseGAN#5]
Hi, I am running the test code with the downloaded data and checkpoints. However, the code stops at loading.

RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for dc1.conv2d.conv_block.0.weight_orig: copying a param with shape torch.Size([1024, 512, 4, 4]) from checkpoint, the shape in current model is torch.Size([512, 512, 4, 4]).
        size mismatch for dc1.conv2d.conv_block.0.weight_v: copying a param with shape torch.Size([16384]) from checkpoint, the shape in current model is torch.Size([8192]).

**Comment by arcchang1236** [comment]
Sorry for the late reply!
I test my code in a new environment and run it successfully.
I think you can create an environment with the same settings in README first.

Thanks
